version: '3.7'
services:
  web:
    build: .
    environment:
      - STAGE_ENV=${STAGE_ENV-development}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - AWS_PROFILE=${AWS_PROFILE-default}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION-us-east-2}
      - SAM_CLI_TELEMETRY=0
      - DIDPWD=${PWD}
    volumes:
      - ~/.aws:/root/.aws:delegated
      - .:/var/task:delegated
      - /var/run/docker.sock:/var/run/docker.sock
    command: "sam local start-api --host '0.0.0.0' --port 3030 --docker-volume-basedir ${PWD}"
    ports:
      - 3030:3030
