AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SpaceStone

Parameters:

  StageEnv:
    Type: String
    Default: staging
    AllowedValues:
      - test
      - development
      - staging
      - production

Resources:

  SpaceStoneLambdaDownload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lib/space_stone.download
      # TODO: Split gems into separate layer; other libs not necessary for download step
      Layers:
        - !Ref ProcessDocumentLayer
      Runtime: ruby3.2
      Timeout: 900
      MemorySize: 512
      EphemeralStorage:
        Size: 10240
      FunctionName: !Sub space-stone-${StageEnv}-download
      Environment:
        Variables:
          STAGE_ENV: !Ref StageEnv
          RUBYOPT: '-W0'
          OCR_QUEUE_URL: !GetAtt SqsQueueOcr.QueueUrl
      Events:
        SpaceStoneHttpApiProxy:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /download
            ApiId: !Ref SpaceStoneHttpApi
        SqsTrigger:
          Type: SQS
          Properties:
            BatchSize: 5
            Queue: !GetAtt SqsQueueDownload.Arn
      Policies:
        - S3FullAccessPolicy:
            BucketName: '*'
        - SQSPollerPolicy:
            QueueName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'

  SpaceStoneLambdaOcr:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lib/space_stone.ocr
      Layers:
        - !Ref ProcessDocumentLayer
      Runtime: ruby3.2
      Timeout: 900
      MemorySize: 512
      EphemeralStorage:
        Size: 2560
      FunctionName: !Sub space-stone-${StageEnv}-ocr
      Environment:
        Variables:
          STAGE_ENV: !Ref StageEnv
          RUBYOPT: '-W0'
      Events:
        SpaceStoneHttpApiProxy:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /ocr
            ApiId: !Ref SpaceStoneHttpApi
        SqsTrigger:
          Type: SQS
          Properties:
            BatchSize: 5
            Queue: !GetAtt SqsQueueOcr.Arn
      Policies:
        - S3FullAccessPolicy:
            BucketName: '*'
        - SQSPollerPolicy:
            QueueName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'

  SpaceStoneLambdaThumbnail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lib/space_stone.thumbnail
      Layers:
        - !Ref ProcessDocumentLayer
      Runtime: ruby3.2
      Timeout: 900
      MemorySize: 4096
      EphemeralStorage:
        Size: 1280
      FunctionName: !Sub space-stone-${StageEnv}-thumbnail
      Environment:
        Variables:
          STAGE_ENV: !Ref StageEnv
          RUBYOPT: '-W0'
      Events:
        SpaceStoneHttpApiProxy:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /thumbnail
            ApiId: !Ref SpaceStoneHttpApi
        SqsTrigger:
          Type: SQS
          Properties:
            BatchSize: 1
            Queue: !GetAtt SqsQueueThumbnail.Arn
      Policies:
        - S3FullAccessPolicy:
            BucketName: '*'
        - SQSPollerPolicy:
            QueueName: '*'
        - SQSSendMessagePolicy:
            QueueName: '*'


  SpaceStoneHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageEnv
      Tags:
        env: !Ref StageEnv
        group: shared
        application: space-stone

  SqsQueueFailed:
   Type: AWS::SQS::Queue
   Properties:
     QueueName: space-stone-failed-queue
     VisibilityTimeout: 900
     RedriveAllowPolicy:
       redrivePermission: allowAll
     Tags:
       - Key: Name
         Value: space-stone-failed-queue
       - Key: application
         Value: space-stone

  SqsQueueDownload:
   Type: AWS::SQS::Queue
   Properties:
     QueueName: space-stone-download-queue
     VisibilityTimeout: 900
     RedrivePolicy:
       deadLetterTargetArn: !GetAtt SqsQueueFailed.Arn
       maxReceiveCount: 2
     Tags:
       - Key: Name
         Value: space-stone-download-queue
       - Key: application
         Value: space-stone

  SqsQueueOcr:
   Type: AWS::SQS::Queue
   Properties:
     QueueName: space-stone-ocr-queue
     VisibilityTimeout: 900
     RedrivePolicy:
       deadLetterTargetArn: !GetAtt SqsQueueFailed.Arn
       maxReceiveCount: 10
     Tags:
       - Key: Name
         Value: space-stone-ocr-queue
       - Key: application
         Value: space-stone

  SqsQueueThumbnail:
   Type: AWS::SQS::Queue
   Properties:
     QueueName: space-stone-thumbnail-queue
     VisibilityTimeout: 900
     RedrivePolicy:
       deadLetterTargetArn: !GetAtt SqsQueueFailed.Arn
       maxReceiveCount: 10
     Tags:
       - Key: Name
         Value: space-stone-thumbnail-queue
       - Key: application
         Value: space-stone

  ProcessDocumentLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ProcessDocumentLayer
      Description: add tesseract, imagemagick for ocr
      ContentUri: layers/process_documents/ProcessDocumentLayer.zip
      CompatibleRuntimes:
        - ruby3.2
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
Outputs:

  SpaceStoneLambdaDownlaodArn:
    Description: Download Lambda Function Arn
    Value: !GetAtt SpaceStoneLambdaDownload.Arn

  SpaceStoneLambdaOcrArn:
    Description: Ocr Lambda Function Arn
    Value: !GetAtt SpaceStoneLambdaOcr.Arn

  SpaceStoneLambdaThumbnailArn:
    Description: Thumbnail Lambda Function Arn
    Value: !GetAtt SpaceStoneLambdaThumbnail.Arn

  SpaceStoneInvokeUrl:
    Description: Lambda Invoke URL
    Value: !Sub "https://${SpaceStoneHttpApi}.execute-api.${AWS::Region}.amazonaws.com/${StageEnv}/"

  SpaceStoneSqsDownload:
    Description: SQS for downloads
    Value: !GetAtt SqsQueueDownload.QueueName

  SpaceStoneSqsOcr:
    Description: SQS for ocr
    Value: !GetAtt SqsQueueOcr.QueueName

  SpaceStoneSqsThumbnail:
    Description: SQS for thumbnails
    Value: !GetAtt SqsQueueThumbnail.QueueName
